In [ ]:
#Dataset 2 with agentic AI

In [ ]:
!free -h

               total        used        free      shared  buff/cache   available
Mem:            12Gi       1.9Gi       7.7Gi       2.0Mi       3.1Gi        10Gi
Swap:             0B          0B          0B

In [ ]:
from google.colab import files
uploaded_file=files.upload()

Saving Mental Distress Dataset-original.csv to Mental Distress Dataset-original (1).csv

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [ ]:
df=pd.read_csv("Mental Distress Dataset-original.csv")

In [ ]:
df.head()

                                                text     label
0  I have been (passively at best, actively at wo...  Suicidal
1  Idk when or how but soon. I will likely hang m...  Suicidal
2  I used to say that I would not commit suicide ...  Suicidal
3  Just so I can work minimum wage for 40 years w...  Suicidal
4  for a little while, i did everything right. i ...  Suicidal

In [ ]:
df['text']=df['text'].str.lower()

In [ ]:
df.head()

                                                text     label
0  i have been (passively at best, actively at wo...  Suicidal
1  idk when or how but soon. i will likely hang m...  Suicidal
2  i used to say that i would not commit suicide ...  Suicidal
3  just so i can work minimum wage for 40 years w...  Suicidal
4  for a little while, i did everything right. i ...  Suicidal

In [ ]:
#Converting columns contatining text data to numeric data

In [ ]:
import string
exclude=string.punctuation

In [ ]:
def remove_punc(text):
  # Ensure text is treated as a string to avoid AttributeError with floats (NaNs)
  text = str(text)
  return text.translate(str.maketrans('','',exclude))
df['text']=df['text'].apply(remove_punc)

In [ ]:
df.head()

                                                text     label
0  i have been passively at best actively at wors...  Suicidal
1  idk when or how but soon i will likely hang my...  Suicidal
2  i used to say that i would not commit suicide ...  Suicidal
3  just so i can work minimum wage for 40 years w...  Suicidal
4  for a little while i did everything right i wa...  Suicidal

In [ ]:
#Bert tokenizer
from transformers import BertTokenizer, BertModel
import torch

# 1. Load tokenizer & model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

# 2. Preprocess text
inputs = tokenizer(df['text'].tolist(),batch_size=8, return_tensors="pt", padding=True, truncation=True)

# 3. Get embeddings
outputs = model(**inputs)
embedding = outputs.last_hidden_state[:,0,:]  # CLS token embedding

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [ ]:
#Bert embedding
import torch
from transformers import AutoTokenizer, AutoModel

# 1. Load the pre-trained BERT tokenizer and model
model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# 2. Define the input text
text = "Python code for BERT embeddings is highly efficient."

# 3. Tokenize input and convert to PyTorch tensors
inputs = tokenizer(
    text,
    return_tensors="pt",
    padding=True,
    truncation=True,
    add_special_tokens=True
)

# 4. Generate embeddings without tracking gradients (inference mode)
with torch.no_grad():
    outputs = model(**inputs)

# 5. Extract specific types of embeddings

# A. Word/Token-Level Embeddings
# Shape: [batch_size, sequence_length, hidden_dimension] -> (1, sequence_length, 768)
word_embeddings = outputs.last_hidden_state

# B. Sentence-Level Embedding Option 1: [CLS] Token
# The first token ([CLS]) represents the aggregated sentence meaning
sentence_embedding_cls = word_embeddings[0, 0, :]

# C. Sentence-Level Embedding Option 2: Mean Pooling (Recommended)
# Average out all token embeddings across the sequence length dimension
sentence_embedding_mean = word_embeddings.mean(dim=1).squeeze()

# Print results and tensor shapes
print(f"Token Embeddings Shape: {word_embeddings.shape}")
print(f"CLS Sentence Embedding Shape: {sentence_embedding_cls.shape}")
print(f"Mean Pooled Sentence Embedding Shape: {sentence_embedding_mean.shape}")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Token Embeddings Shape: torch.Size([1, 14, 768])
CLS Sentence Embedding Shape: torch.Size([768])
Mean Pooled Sentence Embedding Shape: torch.Size([768])

In [ ]:
from nltk import sent_tokenize , word_tokenize
import nltk
nltk.download('punkt_tab')

import pandas as pd
if 'text' not in df.columns:
    # Load the full original dataset to retrieve the 'statement' column
    original_full_df = pd.read_csv("Mental Distress Dataset-original.csv")
    # Assuming the row order hasn't changed, add the column back to df.
    df['text'] = original_full_df['text']

sent_tokens=sent_tokenize(df['text'].astype(str).str.cat(sep=' '))
sent_tokens

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

['i have been passively at best actively at worst suicidal for more years 14 than i have not been at this point it feels like a cancer that i just cannot cut out no matter what meds i take or what positive life changes i make when i go to bed at night or take depression naps i cannot help but think of how nice it would be if i died in my sleep i beg the universe for it sometimes especially with the trajectory of the worldand if i am not supposed to die then i wish that life could just pause for a few seconds i am struggling to breathe and its maddening not having adequate space to even attempt to work through these awful feelings how do i tell my job friends family that my daily performance is suffering because i wish i was dead how do i provide for myself if i am in longterm treatment rent does not go away responsibilities will pile up i am so worried that if i acknowledge how bad things are and try to seek help that my life would only get worse and that it would be impossible to claw myself out of that holepeople expect you to keep going like nothing is the matter if you give them the pg version of your thoughts or they start treating you like you are crazy if you are too honest with themand there is no way i could responsibly start a family like this or accomplish any of lifes basic milestones i worry that adoption agencies would flag me in an instant if i tried getting help i cried for hours today just thinking of how irresponsible id be getting a dog and dragging it down with my mood let alone putting a partner or kid through this misery these basic things feel so unattainable and that is killing mei feel like there is no way to win while keeping my pride intact and i am starting to get tired of trying i hate attention but there is no way for me to get the help i need without having to take a break from work i need more than twice monthly therapy at this point but if this feeling never goes away then why put myself through that humiliationno matter what i do there is always that emptiness eating away at my progress the fleeting moments of happiness feel duller each time they come and go i am not interested in anything anymore every single thing in my life is just going through the motions i am numb to everything and the it gets better thing sounds more and more like a lie with each passing dayi am just so tired and i have all but resigned myself to putting my head on my pillow every night and hoping i do not wake up does this feeling ever go away idk when or how but soon i will likely hang myself idk if i will do it at home or at a hotel idk if i want my friends to find me like that i just have to make myself do it at some point when no one is home i have to pay rent soon and i refuse to spend what little time i have left working my friends will keep bitching at me to get a job but it will not matter within a few days i am scared and hesitant to do it but i know i have to see ya soon i used to say that i would not commit suicide because i would not want the people who love me to be devastated i know people love me i know life could be worse which makes this feeling more confusing and sad i am at a point where the feeling of lonliness and sadness and just how much i hate myself have gotten to be too much i still know how devastated my parents would be but it is so painful being alive that i do not feel guilty for leaving because it will make me feel better its just getting really hard now i am physically and mentally exhausted and i just really do not have the strength to go on everything hurts so bad it never stops i thought it would years ago i feel so hurt and lost and like i am not meant to keep going i am still trying but i just want to feel better and i do not think i will until i let go i do not know anymore just so i can work minimum wage for 40 years with no kids or live in my life fuck that god knows i am making it nowhere might as well save everyone the trouble i know i am hopeless regardless why stay for a little while i did everything right i was finally on a schedule i was more social i had more hobbies and then one inconvenience today reminded me why i wanted to die in the first place i hope tomorrow never comesi am fucking trapped here i need to leave right now please let me go this is fucking torture i cannot do it anymore nothing hurts more than going back to breaking down when you thought you were improving i probably going to ramble a bit so sorry about thatalso sorry for bad english i have not found motivation to fix anything in my life for a long time now it is not that i want to die luckily i did not really had those thoughts for a while now altho the ocasionall thought does appear but as fast as it apeared it dissapears too i would like to fix my life but putting effort into something worthless does not seem ok for me sounds like a waste of time because i cannot change at least it feels like it i cannot exactly describe how do i feel everything feels grey even the thoughts in my head weather it be good or bad it just has this emptiness feel to it but not in a bad way i would like to change but i do not want to change either i do not even feel motivation to kill myself i mean why bother it only going to because pain to others some might even blame themselves and this feeling of emptiness would just go to the other person i hate to talk about these things because there are people who has a harder life than i do i mean i am posting on a site where are peoples who went trough the worst shit has a traumatic sad life yet here i am complaining and whine like a little kid kind of feels like my feelings are not valid in any way or form maybe i am just selfish i do not know anymore heck i never knew anything honestly i do not know what i want or need anymore honestly i know i want to die and end my worthless existence yet i hate the fact that my survival instinct kicks in and stops me it makes me hate myself even more which leads me further to wanting to die it is an endless loop i am trapped in this is why i will never resent someone who would murder me and would be grateful to them for doing what i could not i wish i had the courage to kill myself do any of you just that this feeling that if someone held you for a bit maybe everything will be okayi mean like holding you as you cry and mumble about your troubles maybe rubbing your back or patting your head reassuringly never discouraging you from your emotions only letting you and your saddness exist with them maybe whispering let it out or its okay or even it is all going to be okay without ever shushing you maybe i am just that bad though i would be lying if i said i did not find comfort in this pathetic fantasygod this just makes me feel more ashamed of my feelings i have never attempted to yet but i cannot help feeling like i do not want to exist anymore surely i do not really have a right to complain when i have never fought the battle righteither way i guess it would just be nice to be with someone who wanted me around who maybe was not repulsed by me at least oncethat might help me avoid the inevitable at this point loneliness really does feel like a slowacting poison i have thought about suicide many times and many times i have also just forgotten about it but with so many problems lately in my life i cannot seem to feel okay about anything anymore my bf rather sleep in the hot car outside than talk things out with me everything is falling apart feeling very down about my relationshiplife i cannot handle with anymore things are starting to align so i know it will be over soon making arrangements for my death the thought to end my life constantly plays in the background of my mind a part of me has made peace with the thought that that is probably going to be the way i die down the road ill get tired of fighting and finally just give in currently i live as an obligation to the people in my life that know me and care for me a part of me knows that i should feel grateful to have people in my life that want me around but i just feel guilt i wish i cared about my life as much as they do i feel bad for them for caring about me and getting attached i just want to disappear i just want to disappear  prior to this extremely sick and twisted prank being pulled on me i was already struggling i am not sure if i would go as far as to say depression since depression is a very serious clinical term i am writing this shortly after having everything revealed to me a month ago my friend introduced me to his fiances friend and set us up on a date we started talking prior to the date and semmed to really hit it off the date itself went great as well fast forward a month now and the girl is upset with me over something i said it was a poor choice of words for sure but it did not warrent a reaction as big as she gave and this confused me i got her flowers to try and make it up to her but she said she still needed space i obviously went along with her wishes and that night she started to post pictures with another guy obviously one that was close with her i was hurt but thought maybe it was just a misunderstanding and decided to ask her before jumping to a conclusion turns out this whole relationship one which had us talking daily going on dates during all of our free time intimacy and sharing of extremely intimate details was a prank for her and my friends fiance to pull on him so yeah before this i was not exactly an outgoing person i was not a social outcast either but now i have got to explain to the friends i introduced her to that i was being played and all for some game her response to all this was unforgiving of course just confusion on why i would be hurt i am at the lowest point ever i am ready for my day when it comes i have it planned out nothing going to change it now wish i could say anything has helped but not a thing cutting is everyday again took like a bunch of benadryl and my boyfriend made me throw it up but i cut myself pretty bad and if i wait until i go to treatment ag the hospital tomorrow it might be too late to stitch whenever i ask people why i should not kill myself the first answer i always receive is because someone loves you they will be sad when you are gonewell what about me what about my sadness you are telling me that i am only supposed to stay alive for the benefit of someone else while i continue to stay here and suffer when someone tells me why i should not do it i am severely ill physically and mentally and i am trying to get help but it is been a year and nothing is really working in the past year i have done residential inpatient php twice and iop and nothing really solves any of my problems i am also seeing multiple medical doctors who are also not helping i do not really want to die but how much longer am i supposed to keep living like this everyone is full of advice and acronyms and thought challenging but i need some god damn bread and roses i am doing the responsible thing following my safety plan being open with my medical team and nothing is helping i am going to kill myself soon after i get a tattoo with my sister after i turn 18 me and my sister were going to get tattoos together after that i plan on finding nitrogen gas you know how the rest goes bye i guess i am completely shaken this lady sounded so insanely bored i have talked to internetprovider customer service workers with more pep and care was in the midst of a crisis at a total loss i could not think straight struggling to talk through tears it was like she did not even listen to what i was sayingi used precious vacation days and spent the last week off from work because of my mental health instead of taking steps to get better like i planned i could not even get off the couch to brush my teeth or cook i have to go back to work tomorrow and know i simply cannot do it i cannot even get dressed but i used up all my vacation days and i desperately need money for the last 5 months until july i was paying two rents because i had to move early due to wfm protocol ending and was just barely scraping by i have a lot of medical debt paying 200month for past therapies i cannot go to a doctor right now i simply do not have the money i already have a 500 backlog of payments to make to my current therapist who is been graciously patient while i get my finances in orderi told her all this and she was like in this flat tone okay what is your plan c as if it was just the easiest thing i could come up with on the spot and i was just stunned in silence for a moment and then just hung upthis just feeds as another sign that this world is horrible and life is not worth living i look desperately for help and cannot find any the top result for google searches of depression hotline or mental health crisis hotline is all ads for things that look like scams it feels so hopelessi just needed to vent i emailed my therapist asking for his guidance so at least tomorrow i will have something to go on just called the suicide prevention hotline i am in absolute shock by how horrible it was i am frustrated with myself i keep failing i hate where i am right now in life cuz i am struggling so much and i am not happy i do not know where i am headed the changes i want to make in my life will not happen cuz every change i try to make there is a wall i cannot get overi am tired i hate myself for not being good enough to the point i dream where i kill and hurt myself i am scared it may come true one day i thought i was doing better but i suddenly relapsed yesterday i did not even realize i gripped myself to hard with my nails and bledi do not know where i am going with this i think i am having a mental breakdown and i am trying to get my sht together but i am losing a grip of myself i do not know what to do with myself anymore i am so tired why cannot i just be like everyone else who can get their sht together i get dreams where i kill myself and i am scared it may come true one day i am drunk enough i am 22 and my life is over i am in therapy and on meds and if that is not even enough to help me nothing is i am going to die alone and ill never have a relationship i hope i do not wake up tomorrow i think tonight is the night i do it i have wanted to die for 20years now life has had its ups and downs i was even happy for a few of those years but even when i am happy i always think to myself was all this worth living and the answer is always noi kept myself alive believing i deserve this suffering i got to deal with because i am being punished for being born and i am not allowed to end my punishment early or my next life or another person will have to deal with this sufferingbut i am really close to giving up once my grandmother passes and i am not needed anymore i think it will be my end as well i give up i cannot take it anymore i am killing myself why are they making me work so much as a minor i have no more days off kind of pumping myself up i left a note saying that if i end up a vegetable to please pull the plug 12 hours to go i cannot feel any sense of joy i want to say i have not been happy since early 2017 when i was still 14 i try to do pleasurable things and accumulate positive experiences like my fuckin dbt manual tells me to but nothing helps or offers a reprieve i lie and put on a fake smile and tell people that i am having a good time but i am not genuine i just do not want to be seen as an ungrateful rude bitch whenever i am doing anything that is supposed to be pleasurable i would rather be lying in bed with all the lights off because whatever it is it cannot make me happy it does nothing but sap me of my emotional energy i have a lovely girlfriend who is an absolute angel but i feel nothing when i am with her even she does not make me happy and that makes me feel evilit is midnight where i am and i am listening to whams last christmas and crying i just need to accept that i am never going to be happy and either learn to live with that or make my plan to sylvia plathmyself life is suffering anhedonia has got me wanting to attempt again still been cutting getting ready for my day and its been getting easier and easier which is harder and harder but wow this world is not worth it no use for anything anymore used to be a kid who called me dad cannot remember the last time someone even said my name now same old the only people who truly understand truly are the ones who have been on the brink who have dipped their toes in the unfamiliar water of death and had to fight themselves not to go back for more the soldiers who are fighting every day to stay alive for other people not for themselves it is a critical defining and monumental moment in a persons life the actual choice whether to live or die most people make that choice every day without even thinking about it they live with a careless contentment in everyday life perhaps annoyance at the obstacles the roadblocks that all get in our way from time to time they have no idea what it feels like to open your eyes and feel an instant dread wash over you clammy hands pounding heart sinking stomach guilt so strong it takes your breath away and you have to remind yourself to take it one day at a time one hour at a time one minute at a time because you cannot bear the thought of sticking around for another day let alone a whole lifetime i am 23 and it has taken everything in me to get to this point i am at the prime of my life and i feel old and decrepid and so so tired an exhaustion that is so all consuming it forces me back into bed every time i try to dig my heels in stay out of it i am a tired old dog who just wants to be put out of its misery if you have never been suicidal you cannot understand i used the online suicide hotline chat and got off the chat and like the idiot i am i forgot to turn on my vpna few hours later midnight 2 officers came knocking on my door and sure enough they traced my ip and got a hold of my address from their dispatch to do a welfare check luckily my suicidal thoughts died down enough to where they evaluated me as not in immediate danger so i was not forced to go to the nearby hospital anyone have similar experiences where you kind of forget that they trace your ip and have police come to check on you police came to my apartment tonight i understand the whole it will get better and better times are ahead spiel hell i have told my alsosuicidal friends that same shit as a pisspoor attempt of trying to convince them not to do it but the easy retort to that at least for me is that every good moment is followed by just a damn shitty existence every time without fail and every time that good thing that everyone says you should stick around for was not fucking worth itokay it will get better but it sure as hell will not stay that way sure it gets better but then it goes right back to being fucking awful i am not suicidal i do not think but i certainly do not feel like i have anymore fight in melife over the past two years especially has been a lot of rollercoaster ups and mostly downs to the point of i am just so tired of fighting for something i do not know if even want i had to move out of my country leaving my family pets and everything i knew behind because of some pretty serious health problems that were stopping me from working could not afford food let alone rent had to movemy one ray of hope in any of the past two years was my significant other for the sake of privacy ill call them bob doe they have been trying their best to help me with everything but they also have an addiction to drugs and alcohol they are never abusive other than the lying and i have given them more chances than i should and they just keep slipping i know i know run away but id have no where to go and no way to get there if i left plus my passport has expired and i just had sudden cardiac arrest in january they are usually pretty good about staying on the right track the drugs and alcohol are just a minor thing compared to all they 

In [ ]:
import pandas as pd
from nltk import word_tokenize

if 'text' not in df.columns:
    original_full_df = pd.read_csv("Mental Distress Dataset-original.csv")
    df['text'] = original_full_df['text']

word_tokens=word_tokenize(df['text'].astype(str).str.cat(sep=' '))
word_tokens

['i',
 'have',
 'been',
 'passively',
 'at',
 'best',
 'actively',
 'at',
 'worst',
 'suicidal',
 'for',
 'more',
 'years',
 '14',
 'than',
 'i',
 'have',
 'not',
 'been',
 'at',
 'this',
 'point',
 'it',
 'feels',
 'like',
 'a',
 'cancer',
 'that',
 'i',
 'just',
 'can',
 'not',
 'cut',
 'out',
 'no',
 'matter',
 'what',
 'meds',
 'i',
 'take',
 'or',
 'what',
 'positive',
 'life',
 'changes',
 'i',
 'make',
 'when',
 'i',
 'go',
 'to',
 'bed',
 'at',
 'night',
 'or',
 'take',
 'depression',
 'naps',
 'i',
 'can',
 'not',
 'help',
 'but',
 'think',
 'of',
 'how',
 'nice',
 'it',
 'would',
 'be',
 'if',
 'i',
 'died',
 'in',
 'my',
 'sleep',
 'i',
 'beg',
 'the',
 'universe',
 'for',
 'it',
 'sometimes',
 'especially',
 'with',
 'the',
 'trajectory',
 'of',
 'the',
 'worldand',
 'if',
 'i',
 'am',
 'not',
 'supposed',
 'to',
 'die',
 'then',
 'i',
 'wish',
 'that',
 'life',
 'could',
 'just',
 'pause',
 'for',
 'a',
 'few',
 'seconds',
 'i',
 'am',
 'struggling',
 'to',
 'breathe',
 'and',
 'its',
 'maddening',
 'not',
 'having',
 'adequate',
 'space',
 'to',
 'even',
 'attempt',
 'to',
 'work',
 'through',
 'these',
 'awful',
 'feelings',
 'how',
 'do',
 'i',
 'tell',
 'my',
 'job',
 'friends',
 'family',
 'that',
 'my',
 'daily',
 'performance',
 'is',
 'suffering',
 'because',
 'i',
 'wish',
 'i',
 'was',
 'dead',
 'how',
 'do',
 'i',
 'provide',
 'for',
 'myself',
 'if',
 'i',
 'am',
 'in',
 'longterm',
 'treatment',
 'rent',
 'does',
 'not',
 'go',
 'away',
 'responsibilities',
 'will',
 'pile',
 'up',
 'i',
 'am',
 'so',
 'worried',
 'that',
 'if',
 'i',
 'acknowledge',
 'how',
 'bad',
 'things',
 'are',
 'and',
 'try',
 'to',
 'seek',
 'help',
 'that',
 'my',
 'life',
 'would',
 'only',
 'get',
 'worse',
 'and',
 'that',
 'it',
 'would',
 'be',
 'impossible',
 'to',
 'claw',
 'myself',
 'out',
 'of',
 'that',
 'holepeople',
 'expect',
 'you',
 'to',
 'keep',
 'going',
 'like',
 'nothing',
 'is',
 'the',
 'matter',
 'if',
 'you',
 'give',
 'them',
 'the',
 'pg',
 'version',
 'of',
 'your',
 'thoughts',
 'or',
 'they',
 'start',
 'treating',
 'you',
 'like',
 'you',
 'are',
 'crazy',
 'if',
 'you',
 'are',
 'too',
 'honest',
 'with',
 'themand',
 'there',
 'is',
 'no',
 'way',
 'i',
 'could',
 'responsibly',
 'start',
 'a',
 'family',
 'like',
 'this',
 'or',
 'accomplish',
 'any',
 'of',
 'lifes',
 'basic',
 'milestones',
 'i',
 'worry',
 'that',
 'adoption',
 'agencies',
 'would',
 'flag',
 'me',
 'in',
 'an',
 'instant',
 'if',
 'i',
 'tried',
 'getting',
 'help',
 'i',
 'cried',
 'for',
 'hours',
 'today',
 'just',
 'thinking',
 'of',
 'how',
 'irresponsible',
 'id',
 'be',
 'getting',
 'a',
 'dog',
 'and',
 'dragging',
 'it',
 'down',
 'with',
 'my',
 'mood',
 'let',
 'alone',
 'putting',
 'a',
 'partner',
 'or',
 'kid',
 'through',
 'this',
 'misery',
 'these',
 'basic',
 'things',
 'feel',
 'so',
 'unattainable',
 'and',
 'that',
 'is',
 'killing',
 'mei',
 'feel',
 'like',
 'there',
 'is',
 'no',
 'way',
 'to',
 'win',
 'while',
 'keeping',
 'my',
 'pride',
 'intact',
 'and',
 'i',
 'am',
 'starting',
 'to',
 'get',
 'tired',
 'of',
 'trying',
 'i',
 'hate',
 'attention',
 'but',
 'there',
 'is',
 'no',
 'way',
 'for',
 'me',
 'to',
 'get',
 'the',
 'help',
 'i',
 'need',
 'without',
 'having',
 'to',
 'take',
 'a',
 'break',
 'from',
 'work',
 'i',
 'need',
 'more',
 'than',
 'twice',
 'monthly',
 'therapy',
 'at',
 'this',
 'point',
 'but',
 'if',
 'this',
 'feeling',
 'never',
 'goes',
 'away',
 'then',
 'why',
 'put',
 'myself',
 'through',
 'that',
 'humiliationno',
 'matter',
 'what',
 'i',
 'do',
 'there',
 'is',
 'always',
 'that',
 'emptiness',
 'eating',
 'away',
 'at',
 'my',
 'progress',
 'the',
 'fleeting',
 'moments',
 'of',
 'happiness',
 'feel',
 'duller',
 'each',
 'time',
 'they',
 'come',
 'and',
 'go',
 'i',
 'am',
 'not',
 'interested',
 'in',
 'anything',
 'anymore',
 'every',
 'single',
 'thing',
 'in',
 'my',
 'life',
 'is',
 'just',
 'going',
 'through',
 'the',
 'motions',
 'i',
 'am',
 'numb',
 'to',
 'everything',
 'and',
 'the',
 'it',
 'gets',
 'better',
 'thing',
 'sounds',
 'more',
 'and',
 'more',
 'like',
 'a',
 'lie',
 'with',
 'each',
 'passing',
 'dayi',
 'am',
 'just',
 'so',
 'tired',
 'and',
 'i',
 'have',
 'all',
 'but',
 'resigned',
 'myself',
 'to',
 'putting',
 'my',
 'head',
 'on',
 'my',
 'pillow',
 'every',
 'night',
 'and',
 'hoping',
 'i',
 'do',
 'not',
 'wake',
 'up',
 'does',
 'this',
 'feeling',
 'ever',
 'go',
 'away',
 'idk',
 'when',
 'or',
 'how',
 'but',
 'soon',
 'i',
 'will',
 'likely',
 'hang',
 'myself',
 'idk',
 'if',
 'i',
 'will',
 'do',
 'it',
 'at',
 'home',
 'or',
 'at',
 'a',
 'hotel',
 'idk',
 'if',
 'i',
 'want',
 'my',
 'friends',
 'to',
 'find',
 'me',
 'like',
 'that',
 'i',
 'just',
 'have',
 'to',
 'make',
 'myself',
 'do',
 'it',
 'at',
 'some',
 'point',
 'when',
 'no',
 'one',
 'is',
 'home',
 'i',
 'have',
 'to',
 'pay',
 'rent',
 'soon',
 'and',
 'i',
 'refuse',
 'to',
 'spend',
 'what',
 'little',
 'time',
 'i',
 'have',
 'left',
 'working',
 'my',
 'friends',
 'will',
 'keep',
 'bitching',
 'at',
 'me',
 'to',
 'get',
 'a',
 'job',
 'but',
 'it',
 'will',
 'not',
 'matter',
 'within',
 'a',
 'few',
 'days',
 'i',
 'am',
 'scared',
 'and',
 'hesitant',
 'to',
 'do',
 'it',
 'but',
 'i',
 'know',
 'i',
 'have',
 'to',
 'see',
 'ya',
 'soon',
 'i',
 'used',
 'to',
 'say',
 'that',
 'i',
 'would',
 'not',
 'commit',
 'suicide',
 'because',
 'i',
 'would',
 'not',
 'want',
 'the',
 'people',
 'who',
 'love',
 'me',
 'to',
 'be',
 'devastated',
 'i',
 'know',
 'people',
 'love',
 'me',
 'i',
 'know',
 'life',
 'could',
 'be',
 'worse',
 'which',
 'makes',
 'this',
 'feeling',
 'more',
 'confusing',
 'and',
 'sad',
 'i',
 'am',
 'at',
 'a',
 'point',
 'where',
 'the',
 'feeling',
 'of',
 'lonliness',
 'and',
 'sadness',
 'and',
 'just',
 'how',
 'much',
 'i',
 'hate',
 'myself',
 'have',
 'gotten',
 'to',
 'be',
 'too',
 'much',
 'i',
 'still',
 'know',
 'how',
 'devastated',
 'my',
 'parents',
 'would',
 'be',
 'but',
 'it',
 'is',
 'so',
 'painful',
 'being',
 'alive',
 'that',
 'i',
 'do',
 'not',
 'feel',
 'guilty',
 'for',
 'leaving',
 'because',
 'it',
 'will',
 'make',
 'me',
 'feel',
 'better',
 'its',
 'just',
 'getting',
 'really',
 'hard',
 'now',
 'i',
 'am',
 'physically',
 'and',
 'mentally',
 'exhausted',
 'and',
 'i',
 'just',
 'really',
 'do',
 'not',
 'have',
 'the',
 'strength',
 'to',
 'go',
 'on',
 'everything',
 'hurts',
 'so',
 'bad',
 'it',
 'never',
 'stops',
 'i',
 'thought',
 'it',
 'would',
 'years',
 'ago',
 'i',
 'feel',
 'so',
 'hurt',
 'and',
 'lost',
 'and',
 'like',
 'i',
 'am',
 'not',
 'meant',
 'to',
 'keep',
 'going',
 'i',
 'am',
 'still',
 'trying',
 'but',
 'i',
 'just',
 'want',
 'to',
 'feel',
 'better',
 'and',
 'i',
 'do',
 'not',
 'think',
 'i',
 'will',
 'until',
 'i',
 'let',
 'go',
 'i',
 'do',
 'not',
 'know',
 'anymore',
 'just',
 'so',
 'i',
 'can',
 'work',
 'minimum',
 'wage',
 'for',
 '40',
 'years',
 'with',
 'no',
 'kids',
 'or',
 'live',
 'in',
 'my',
 'life',
 'fuck',
 'that',
 'god',
 'knows',
 'i',
 'am',
 'making',
 'it',
 'nowhere',
 'might',
 'as',
 'well',
 'save',
 'everyone',
 'the',
 'trouble',
 'i',
 'know',
 'i',
 'am',
 'hopeless',
 'regardless',
 'why',
 'stay',
 'for',
 'a',
 'little',
 'while',
 'i',
 'did',
 'everything',
 'right',
 'i',
 'was',
 'finally',
 'on',
 'a',
 'schedule',
 'i',
 'was',
 'more',
 'social',
 'i',
 'had',
 'more',
 'hobbies',
 'and',
 'then',
 'one',
 'inconvenience',
 'today',
 'reminded',
 'me',
 'why',
 'i',
 'wanted',
 'to',
 'die',
 'in',
 'the',
 'first',
 'place',
 'i',
 'hope',
 'tomorrow',
 'never',
 'comesi',
 'am',
 'fucking',
 'trapped',
 'here',
 'i',
 'need',
 'to',
 'leave',
 'right',
 'now',
 'please',
 'let',
 'me',
 'go',
 'this',
 'is',
 'fucking',
 'torture',
 'i',
 'can',
 'not',
 'do',
 'it',
 'anymore',
 'nothing',
 'hurts',
 'more',
 'than',
 'going',
 'back',
 'to',
 'breaking',
 'down',
 'when',
 'you',
 'thought',
 'you',
 'were',
 'improving',
 'i',
 'probably',
 'going',
 'to',
 'ramble',
 'a',
 'bit',
 'so',
 'sorry',
 'about',
 'thatalso',
 'sorry',
 'for',
 'bad',
 'english',
 'i',
 'have',
 'not',
 'found',
 'motivation',
 'to',
 'fix',
 'anything',
 'in',
 'my',
 'life',
 'for',
 'a',
 'long',
 'time',
 'now',
 'it',
 'is',
 'not',
 'that',
 'i',
 'want',
 'to',
 'die',
 'luckily',
 'i',
 'did',
 'not',
 'really',
 'had',
 'those',
 'thoughts',
 'for',
 'a',
 'while',
 'now',
 'altho',
 'the',
 'ocasionall',
 'thought',
 'does',
 'appear',
 'but',
 'as',
 'fast',
 'as',
 'it',
 'apeared',
 'it',
 'dissapears',
 'too',
 'i',
 'would',
 'like',
 'to',
 'fix',
 'my',
 'life',
 'but',
 'putting',
 'effort',
 'into',
 'something',
 'worthless',
 'does',
 'not',
 'seem',
 'ok',
 'for',
 'me',
 'sounds',
 'like',
 'a',
 'waste',
 'of',
 'time',
 'because',
 'i',
 'can',
 'not',
 'change',
 'at',
 'least',
 'it',
 'feels',
 'like',
 ...]

In [ ]:
#Converting multiple text columns to tokens
text_columns = df.select_dtypes(include='object').columns
print("Text columns in the DataFrame:", text_columns)

Text columns in the DataFrame: Index(['text', 'label'], dtype='object')

In [ ]:
import pandas as pd
if 'text' not in df.columns:
    original_full_df = pd.read_csv("Mental Distress Dataset-original.csv")
    df['text'] = original_full_df['text']

for col in text_columns:
    if col != 'text': # job_role was already tokenized
        df[col + '_tokens'] = df[col].astype(str).apply(word_tokenize)

df.head()

                                                text     label label_tokens
0  i have been passively at best actively at wors...  Suicidal   [Suicidal]
1  idk when or how but soon i will likely hang my...  Suicidal   [Suicidal]
2  i used to say that i would not commit suicide ...  Suicidal   [Suicidal]
3  just so i can work minimum wage for 40 years w...  Suicidal   [Suicidal]
4  for a little while i did everything right i wa...  Suicidal   [Suicidal]

In [1]:
!git config --global user.email "ishitamaurya1010@gmail.com"
!git config --global user.name "Ishita Maurya"

In [2]:
!git clone https://github.com/ishitamaurya1010-cyber/Ishita-Maurrya-Agentic-AI
%cd Ishita-Maurrya-Agentic-AI

Cloning into 'Ishita-Maurrya-Agentic-AI'...
warning: You appear to have cloned an empty repository.
/content/Ishita-Maurrya-Agentic-AI

In [4]:
!git add .
!git commit -m "BERT embeddings code file"

On branch main

Initial commit

nothing to commit (create/copy files and use "git add" to track)